---

- name: Ensure Nginx CGI Param Files
  become: yes
  template:
    src: nginx/{{ item }}.j2
    dest: /etc/nginx/includes/{{ dashboard.name }}_{{ item }}
  with_items:
    - fastcgi_params
  notify:
    - reload nginx

- name: Creates Dashboard site
  become: yes
  template:
    src: nginx/site.j2
    dest: "/etc/nginx/sites-available/{{ dashboard.name }}"
  notify:
    - reload nginx

- name: Enables Dashboard site
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ dashboard.name }}"
    dest: "/etc/nginx/sites-enabled/{{ dashboard.name }}"
    state: link
    force: yes
  notify:
    - reload nginx

- name: Ensure Dashboard is running
  become: yes
  service:
    name: dashboard
    state: running
